(() => {
  const invoke = (command, args) => window.__TAURI_INTERNALS__?.invoke(command, args) ?? Promise.reject(new Error('圈选能力未提供'));
  const selector = document.querySelector('#selector'), selection = document.querySelector('#selection'), review = document.querySelector('#review'), preview = document.querySelector('#preview'), status = document.querySelector('#status'), stroke = document.querySelector('#stroke'), line = stroke.querySelector('polyline'), hint = document.querySelector('#hint');
  let start, points, timer, openedAt = 0, mode = 'rect';
  const close = () => invoke('region_preview_close').catch(() => {});
  const clear = () => { start = points = undefined; selection.hidden = stroke.hidden = review.hidden = true; preview.removeAttribute('src'); clearTimeout(timer); };
  const armTimeout = () => { clearTimeout(timer); timer = setTimeout(close, 30000); };
  const rectFor = point => { const x=Math.min(start.x,point.x), y=Math.min(start.y,point.y), width=Math.abs(start.x-point.x), height=Math.abs(start.y-point.y); return {x,y,width,height,viewportWidth:innerWidth,viewportHeight:innerHeight}; };
  const drawRect = point => { const rect = rectFor(point); Object.assign(selection.style,{left:`${rect.x}px`,top:`${rect.y}px`,width:`${rect.width}px`,height:`${rect.height}px`}); selection.hidden=false; return rect; };
  const drawStroke = point => { points.push(point); stroke.hidden=false; line.setAttribute('points', points.map(({x,y}) => `${x},${y}`).join(' ')); const xs=points.map(({x}) => x), ys=points.map(({y}) => y); return {x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys),viewportWidth:innerWidth,viewportHeight:innerHeight}; };
  const setMode = next => { mode=next; document.querySelector('#rect-mode').setAttribute('aria-pressed',String(mode==='rect')); document.querySelector('#stroke-mode').setAttribute('aria-pressed',String(mode==='stroke')); hint.textContent=mode==='rect'?'拖动鼠标框选内容，按 Esc 取消':'按住鼠标画出笔画，截图取笔画外接矩形'; };
  const showReview = async rect => { try { await invoke('region_preview_hide_for_capture'); await new Promise(resolve => setTimeout(resolve,120)); preview.src=`data:image/png;base64,${await invoke('region_preview_capture',{rect})}`; selector.hidden=true; review.hidden=false; await invoke('region_preview_show_review',{rect}); } catch(error) { selector.hidden=true; review.hidden=false; preview.removeAttribute('src'); status.textContent=error.message||'截图不可用'; await invoke('region_preview_show_review',{rect}).catch(() => {}); } };
  selector.addEventListener('pointerdown', event => { if (event.button !== 0 || event.target.closest('button') || Date.now()-openedAt<350) return; start={x:event.clientX,y:event.clientY}; points=mode==='stroke'?[start]:undefined; if (mode==='stroke') { stroke.hidden=false; line.setAttribute('points',`${start.x},${start.y}`); } selector.setPointerCapture(event.pointerId); armTimeout(); });
  selector.addEventListener('pointermove', event => { if (start) mode==='rect'?drawRect({x:event.clientX,y:event.clientY}):drawStroke({x:event.clientX,y:event.clientY}); });
  selector.addEventListener('pointerup', async event => { if (!start) return; const point={x:event.clientX,y:event.clientY}, rect=mode==='rect'?drawRect(point):drawStroke(point); start=points=undefined; if (rect.width<12||rect.height<12) return clear(); await showReview(rect); });
  document.querySelector('#rect-mode').addEventListener('click', () => setMode('rect')); document.querySelector('#stroke-mode').addEventListener('click', () => setMode('stroke')); document.querySelector('#close').addEventListener('click', close); document.querySelector('#cancel').addEventListener('click', close); document.querySelector('#again').addEventListener('click', () => { clear(); invoke('region_preview_reselect').catch(close); });
  addEventListener('keydown', event => { if (event.key==='Escape') { event.preventDefault(); close(); } });
  addEventListener('yonda-region-open', () => { clear(); openedAt=Date.now(); stroke.setAttribute('viewBox',`0 0 ${innerWidth} ${innerHeight}`); selector.hidden=false; setMode('rect'); status.textContent='仅在本机内存预览；发送给 Agent 的功能待接入。'; armTimeout(); });
})();
