#!/usr/bin/env python3
"""通过正式 UDS 与真实 trycua 计划执行验证控制卡、步骤展示及显式接管。"""
import json,pathlib,socket,sqlite3,subprocess,sys,time
root=pathlib.Path(__file__).resolve().parents[2];out=pathlib.Path(sys.argv[1]);out.mkdir(parents=True,exist_ok=False);watcher=out/"watch-control";subprocess.run(["swiftc",str(root/"apps/desktop/check-cua-control-macos.swift"),"-o",str(watcher)],check=True,timeout=45);expected_fast_decision="已交回慢脑重新观察或规划";native=subprocess.Popen([str(watcher),str(out/"native"),expected_fast_decision,"observe-only"],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
stream=socket.socket(socket.AF_UNIX,socket.SOCK_STREAM);stream.settimeout(60);stream.connect(str(pathlib.Path.home()/"Library/Application Support/com.yonder.desktop/agent.sock"));f=stream.makefile("rwb",buffering=0);counter=0
def call(method,capability,**params):
 global counter;counter+=1;request={"jsonrpc":"2.0","id":f"cua-control-{counter}","method":method,"params":{"agent_id":"codex-cli","capability":capability,"deadline":int(time.time()*1000)+50000,**params}};f.write(json.dumps(request,ensure_ascii=False).encode()+b"\n");response=json.loads(f.readline());assert "error" not in response,response;return response["result"]
try:
 hello=call("gateway.hello","task.read",protocol_version={"major":1,"minor":31});caps={item["name"]:item["availability"] for item in hello["capabilities"]};assert caps.get("task.plan.execute")=="available",caps
 cleanup=sqlite3.connect(pathlib.Path.home()/"Library/Application Support/com.yonder.desktop/tasks.db").execute("SELECT id,state,sequence FROM tasks WHERE name=? AND state IN ('created','running')",("CUA 显式接管原生验证",)).fetchall()
 for task_id,status,sequence in cleanup:
  if status=="running":call("task.complete","task.complete",task_id=task_id,expected_sequence=str(sequence))
  else:call("task.cancel","task.cancel",task_id=task_id,expected_sequence=str(sequence))
 task=call("task.create","task.create",idempotency_key=f"explicit-cua-takeover-{time.time_ns()}",description="验证 CUA 顶部控制条、规划执行步骤与显式接管",name="CUA 显式接管原生验证")["task"]
 slots=[{"step_id":f"tab-{index}","label":f"连续 CUA 步骤 {index}","candidates":[{"candidate_id":f"press-tab-{index}","tool_name":"press_key","arguments":{"key":"tab","delivery_mode":"background"},"action_kind":"resolve-conversation","target_ref":"current-window","preconditions":[{"fact":"target-resolved","expected":True}],"expected_observe":[{"fact":"target-resolved","expected":True}]}]} for index in range(1,9)];slots[0]["candidates"].append({**slots[0]["candidates"][0],"candidate_id":"press-tab-alternate-1"});submitted=call("task.plan.submit","task.plan.submit",task_id=task["task_id"],expected_sequence=task["sequence"],plan_id="explicit-control-plan",plan_version=1,token_budget=100,slots=slots);executed=call("task.plan.execute","task.plan.execute",task_id=task["task_id"],expected_sequence=submitted["sequence"],plan_id="explicit-control-plan",plan_version=1)
 stdout,stderr=native.communicate(timeout=25);assert native.returncode==0,(native.returncode,stdout,stderr);assert executed.get("disposition")=="handback",executed;cancelled=call("task.cancel","task.cancel",task_id=task["task_id"],expected_sequence=executed["sequence"])["task"];db_path=pathlib.Path.home()/"Library/Application Support/com.yonder.desktop/tasks.db"
 with sqlite3.connect(db_path) as db:
  user_input=db.execute("SELECT count(*) FROM task_attempts WHERE task_id=? AND unknown_reason='user-input'",(task["task_id"],)).fetchone()[0];slot=db.execute("SELECT current_slot FROM task_plan_fragments WHERE task_id=? AND plan_id='explicit-control-plan'",(task["task_id"],)).fetchone()[0]
 window=json.loads((out/"native/window-result.json").read_text());result={"platform":"macos","task_id":task["task_id"],"window_visible":window["visible"],"top_centered_like_region":window["top_centered_like_region"],"expected_size":window["expected_size"],"slow_brain_found":window["slow_brain_found"],"fast_brain_found":window["fast_brain_found"],"fast_decision_found":window["fast_decision_found"],"execution_found":window["execution_found"],"planned_step_found":window["planned_step_found"],"observe_only":window["observe_only"],"task_status":cancelled["status"],"executed_disposition":executed.get("disposition"),"stopped_before_all_slots":slot<8,"new_user_input_unknown_count":user_input,"passed":cancelled["status"]=="cancelled" and executed.get("disposition")=="handback" and slot<8 and user_input==0 and window["top_centered_like_region"] and window["expected_size"] and window["slow_brain_found"] and window["fast_brain_found"] and window["fast_decision_found"] and window["execution_found"] and window["planned_step_found"]};(out/"result.json").write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n");print(json.dumps(result,ensure_ascii=False));assert result["passed"],result
finally:
 if native.poll() is None:native.kill();native.wait()
 f.close();stream.close()
