// 原生验证 CUA 控制条：可见、与圈选工具条同屏顶部居中、按钮可显式接管。
import AppKit
import ApplicationServices
guard (2...4).contains(CommandLine.arguments.count),AXIsProcessTrusted(),let app=NSRunningApplication.runningApplications(withBundleIdentifier:"com.yonder.desktop").first else{exit(2)}
let output=URL(fileURLWithPath:CommandLine.arguments[1],isDirectory:true);try FileManager.default.createDirectory(at:output,withIntermediateDirectories:true);let ax=AXUIElementCreateApplication(app.processIdentifier)
let expectedFastDecision=CommandLine.arguments.count>=3 ? CommandLine.arguments[2] : nil
let observeOnly=CommandLine.arguments.count==4 && CommandLine.arguments[3]=="observe-only"
func attr(_ element:AXUIElement,_ name:String)->CFTypeRef?{var value:CFTypeRef?;return AXUIElementCopyAttributeValue(element,name as CFString,&value) == .success ? value:nil}
func find(_ element:AXUIElement,_ title:String,_ depth:Int=0)->AXUIElement?{if attr(element,"AXTitle") as? String == title || attr(element,"AXDescription") as? String == title || attr(element,"AXValue") as? String == title{return element};guard depth<16 else{return nil};for child in attr(element,"AXChildren") as? [AXUIElement] ?? []{if let found=find(child,title,depth+1){return found}};return nil}
func controlWindow()->AXUIElement?{(attr(ax,"AXWindows") as? [AXUIElement] ?? []).first{attr($0,"AXTitle") as? String == "Yonda · 任务执行"}}
func readyWindow()->AXUIElement?{guard let window=controlWindow(),find(window,"Yonder 正在控制您的电脑") != nil,find(window,"慢脑规划") != nil,find(window,"快脑决策") != nil,find(window,"正在执行") != nil,find(window,"连续 CUA 步骤 1") != nil,find(window,"接管电脑") != nil else{return nil};if let expectedFastDecision,find(window,expectedFastDecision)==nil{return nil};return window}
let deadline=ProcessInfo.processInfo.systemUptime+20;while readyWindow()==nil && ProcessInfo.processInfo.systemUptime<deadline{Thread.sleep(forTimeInterval:0.02)}
guard let window=readyWindow(),let positionRaw=attr(window,"AXPosition"),let sizeRaw=attr(window,"AXSize"),CFGetTypeID(positionRaw)==AXValueGetTypeID(),CFGetTypeID(sizeRaw)==AXValueGetTypeID() else{exit(3)};let position=positionRaw as! AXValue;let size=sizeRaw as! AXValue;var point=CGPoint.zero;var dimensions=CGSize.zero;guard AXValueGetValue(position,.cgPoint,&point),AXValueGetValue(size,.cgSize,&dimensions) else{exit(4)}
let center=CGPoint(x:point.x+dimensions.width/2,y:point.y+dimensions.height/2);guard let screen=NSScreen.screens.first(where:{center.x >= $0.visibleFrame.minX-2 && center.x <= $0.visibleFrame.maxX+2}) else{exit(5)};let expectedTop=NSScreen.screens[0].frame.height-screen.visibleFrame.maxY+16;let topCentered=abs(center.x-screen.visibleFrame.midX)<=4 && abs(point.y-expectedTop)<=4
let list=CGWindowListCopyWindowInfo([.optionOnScreenOnly,.excludeDesktopElements],kCGNullWindowID) as? [[String:Any]] ?? [];if let info=list.first(where:{($0[kCGWindowOwnerPID as String] as? Int)==Int(app.processIdentifier)&&($0[kCGWindowName as String] as? String)=="Yonda · 任务执行"}),let id=info[kCGWindowNumber as String] as? Int{let capture=Process();capture.executableURL=URL(fileURLWithPath:"/usr/sbin/screencapture");capture.arguments=["-x","-l",String(id),output.appendingPathComponent("cua-control.png").path];try capture.run();capture.waitUntilExit()}
let messageFound=find(window,"Yonder 正在控制您的电脑") != nil;let slowBrainFound=find(window,"慢脑规划") != nil;let fastBrainFound=find(window,"快脑决策") != nil;let fastDecisionFound=expectedFastDecision.map{find(window,$0) != nil} ?? true;let executionFound=find(window,"正在执行") != nil;let plannedStepFound=find(window,"连续 CUA 步骤 1") != nil;let expectedSize=abs(dimensions.width-560)<=2 && abs(dimensions.height-174)<=2;let button=find(window,"接管电脑");let takeoverPressed=observeOnly ? false : button.map{AXUIElementPerformAction($0,"AXPress" as CFString) == .success} ?? false
let passed=topCentered && expectedSize && messageFound && slowBrainFound && fastBrainFound && fastDecisionFound && executionFound && plannedStepFound && button != nil && (observeOnly || takeoverPressed);let report:[String:Any]=["pid":Int(app.processIdentifier),"visible":true,"top_centered_like_region":topCentered,"position":[point.x,point.y],"expected_top":expectedTop,"size":[dimensions.width,dimensions.height],"expected_size":expectedSize,"message":messageFound,"slow_brain_found":slowBrainFound,"fast_brain_found":fastBrainFound,"fast_decision_found":fastDecisionFound,"execution_found":executionFound,"planned_step_found":plannedStepFound,"button_found":button != nil,"observe_only":observeOnly,"takeover_pressed":takeoverPressed,"passed":passed];let data=try JSONSerialization.data(withJSONObject:report,options:[.prettyPrinted,.sortedKeys]);try data.write(to:output.appendingPathComponent("window-result.json"));print(String(data:data,encoding:.utf8)!);if !passed{exit(6)}
